module
import Models.Main
#print axioms Models.Main.admission
#print axioms Models.Main.admitCosts
#print axioms Models.Main.admit_accepts_cheap
#print axioms Models.Main.admit_rejects_costly
#print axioms Models.Main.classify
#print axioms Models.Main.classifyChecked
#print axioms Models.Main.classify_eight
#print axioms Models.Main.flowCode
#print axioms Models.Main.flowStep
#print axioms Models.Main.flow_accepts
#print axioms Models.Main.flow_refuses_input
#print axioms Models.Main.flow_refuses_junction
#print axioms Models.Main.guessChecked
#print axioms Models.Main.guessOvershoot
#print axioms Models.Main.guessTwice
#print axioms Models.Main.guess_accepts
#print axioms Models.Main.guess_refuses_precondition
#print axioms Models.Main.ledgerFull
#print axioms Models.Main.ledgerPost
#print axioms Models.Main.ledger_accepts
#print axioms Models.Main.ledger_full_accepts
#print axioms Models.Main.ledger_full_refuses_output
#print axioms Models.Main.ledger_refuses_input
#print axioms Models.Main.ledger_refuses_output
#print axioms Models.Main.ledger_refuses_precondition
#print axioms Models.Main.overshootChecked
#print axioms Models.Main.overshoot_pair_refuses_postcondition
#print axioms Models.Main.overshoot_refuses_postcondition
#print axioms Models.Main.respond
#print axioms Models.Main.spillStream
#print axioms Models.Main.step
#print axioms Models.Main.stepCode
#print axioms Models.Main.streamCode
#print axioms Models.Main.stream_accepts
#print axioms Models.Main.stream_refuses_output
#print axioms Models.Main.twiceCode
#print axioms Models.Main.twice_accepts
#print axioms Models.Main.twice_refuses
#print axioms Models.Main.valueCode
